# Python Workshop Notebook

## 1. Python Basics

### Variables and Data Types

In [ ]:
int_ex = 4
float_ex = 3.14
string_ex = "python"
bool_ex = True

In [ ]:
# print the type of the variables
print(type(int_ex))
print(type(float_ex))
print(type(string_ex))
print(type(bool_ex))

In [ ]:
name = "Python Workshop"
session = 2
print(f"Welcome to the {name}! This is session number {session}.")

### Operations

#### Arithmetic Operations

In [ ]:
a = 5
b = 3
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

#### Comparison Operations

In [ ]:
print(5 == 3)
print(5 != 3)
print(5 > 3)
print(5 < 3)
print(5 >= 3)
print(5 <= 3)

#### Logical Operations

In [ ]:
a = True
b = False

print(a and b)  # Logical AND
print(a or b)   # Logical OR
print(not a)    # Logical NOT

#### Assignment Operations 

In [ ]:
x = 5
x += 3  
print(x)

x -= 2  
print(x)

x *= 2  
print(x)

x /= 3  
print(x)

x //= 2  
print(x)

x %= 3  
print(x)

#### Identity Operations

In [ ]:
x = 10
y = 10
z = 15

print(x is y)
print(x is z)
print(y is not z)


#### Membership Operations

In [ ]:
fruits = ["apple", "banana", "cherry"]
print("apple" in fruits)   
print("grape" not in fruits)  


### Conditional Statements (if-else-elif)

In [ ]:
# Check if a number is positive, negative or zero
num = 10
if num > 0:
    print("Number is positive")
elif num < 0:
    print("Number is negative")
else:
    print("Number is zero")

### Loops

For Loop

In [ ]:
for i in range(5):
    if i % 2 == 0:
        print(f"{i} is even")
    else:
        print(f"{i} is odd")

While Loop

In [ ]:
count = 0
while count < 5:
    print(f"Count is {count}")
    count += 1

### Functions

In [ ]:
# A function that adds two numbers
def add(a, b):
    return a + b

print(add(3, 4))

In [ ]:
# A function that takes a name and returns a greeting message
def greet(name):
    return f"Hello, {name}!"

print(greet("Participant"))

### Lists

1. Creating Lists

In [ ]:
# Example of a list
fruits = ["apple", "banana", "cherry"]
print(fruits)

2. Accessing List Elements

In [ ]:
# Accessing elements by index
print(fruits[0])
print(fruits[1])

In [ ]:
# Negative index
print(fruits[-1])
print(fruits[-2])

3. Modifying Lists

In [ ]:
# Modifying a list element
fruits[1] = "orange"  # Replaces 'banana' with 'orange'
print(fruits)

4. Adding Elements to a List

In [ ]:
# Using append to add a single item
fruits.append("grapes")
print(fruits)

# Using insert to add an item at a specific index
fruits.insert(1, "blueberry")  # Insert at index 1
print(fruits)

# Using extend to add multiple items
fruits.extend(["melon", "kiwi"])
print(fruits)

5. Removing Items from a List

In [ ]:
fruits = ["apple", "banana", "cherry"]

# Using remove() to remove a specific item
fruits.remove("banana")
print(fruits)


# Using pop() to remove the last item
fruits.pop()
print(fruits)

fruits = ["apple", "banana", "cherry"]

# Using pop() with an index
fruits.pop(2)  # Removes 'cherry' at index 2
print(fruits)

# Using clear() to remove all items
fruits.clear()
print(fruits) 

6. List Slicing

In [ ]:
# Slicing a list
fruits = ["apple", "banana", "cherry", "date", "elderberry"]
print(fruits[1:4])
print(fruits[:3])
print(fruits[2:])
print(fruits[-3:])

7. List Operations

In [ ]:
# Concatenating lists
fruits = ["apple", "banana"]
more_fruits = ["cherry", "date"]
all_fruits = fruits + more_fruits
print(all_fruits)

# Repeating lists
fruits = ["apple", "banana"]
repeated_fruits = fruits * 2
print(repeated_fruits)

# Checking membership
print("apple" in fruits)
print("grape" in fruits)

## Python Basics Exercise

This notebook contains exercises to practice loops and conditional statements in Python.

1. **Create a List Using a For Loop**  
   - Generate a list of numbers from `1 to 20` using a `for` loop.
   - Fill in the missing parts in the `range()` function and complete the loop logic.

2. **Filter Even Numbers Using a Function**  
   - Write a function `get_even_numbers()` that takes a list of numbers and returns a new list with only even numbers.
   - Complete the `for` loop and condition inside the function.

3. **Iterate Using a While Loop**  
   - Use a `while` loop to print even numbers from the list until a number greater than `15` is encountered.
   - Fill in the missing condition and statements to complete the logic.

Complete the blanks and run the code to test your solutions!


In [ ]:
# 1. Create a list of numbers from 1 to 20 using a for loop
numbers = []
for i in range(____, ____):  # Fill in the range
    pass                     # Replace 'pass' with the code to add the number to the list
print(numbers)

In [ ]:
# 2. Write a function to return only even numbers
def get_even_numbers(num_list):
    even_numbers = []
    for num in ____:    # Fill in the blank
        if ():          # Fill in the condition
            pass        # Replace 'pass' with the correct statement
    return ____         # Replace the blank with the correct variable

In [ ]:
even_numbers = get_even_numbers(____)
print(f"Even numbers: {____}")

In [ ]:
# 3. Use a while loop to print even numbers in the list, until one is greater than 15
index = 0
while (____):                           # Fill in the condition
    pass                            # Replace 'pass' with the correct statements
    pass                            # Replace 'pass' with the correct statements

## 2. Practical Applications

### Install Dependencies

Run

In [ ]:
%pip install -r requirements.txt

or...

In [ ]:
%pip install serial requests matplotlib numpy pandas scikit-learn opencv-python

### Serial Communication

<span style="color:red">(DON'T test this here. Go to the given [Serial Visualization Script](serial_vis.py).
This cell is only to show the base syntax.</span>

The Arduino code is also given: [Open Arduino Code](pot_value_test/pot_value_test.ino))  

### Important Instructions Before Running the Script  

**Upload the Code to Your Arduino Board:**  
1. Open the Arduino IDE.  
2. Load the `pot_value_test.ino` file.  
3. Connect your Arduino board to the PC via USB.  
4. Select the correct **board** and **port** under `Tools → Board` and `Tools → Port`.  
5. Verify the **baud rate** in the code (e.g., `Serial.begin(9600);`).  
6. Click the **Upload** button and wait for the process to complete.  

**Before Running the Python Script:**  
- **Close the Serial Monitor** in the Arduino IDE to prevent port conflicts.  
- Make note of the **COM port** (Windows) or **/dev/ttyUSBx** (Linux/Mac) used by your Arduino.  
- Ensure the baud rate in the Python script matches the one used in your Arduino code.  

Once everything is set, you can run the `serial_vis.py` script to visualize the data.

In [ ]:
import serial

In [ ]:
ser = serial.Serial('COM3', 9600)                   # Change the port to the one used by your Arduino
ser.write(b'Hello Arduino')                         # Send a message to the Arduino
data = ser.readline().decode('utf-8').strip()       # Read the message from the Arduino
print(f"Received: {data}")                          # Print the message
ser.close()

### HTTP Requests

In [16]:
import requests

In [17]:
response = requests.get("https://api.spacexdata.com/v4/launches/latest")
if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(response.status_code)
    print("Failed to fetch data")

{'fairings': None, 'links': {'patch': {'small': 'https://images2.imgbox.com/eb/d8/D1Yywp0w_o.png', 'large': 'https://images2.imgbox.com/33/2e/k6VE4iYl_o.png'}, 'reddit': {'campaign': None, 'launch': 'https://www.reddit.com/r/spacex/comments/xvm76j/rspacex_crew5_launchcoast_docking_discussion_and/', 'media': None, 'recovery': None}, 'flickr': {'small': [], 'original': []}, 'presskit': None, 'webcast': 'https://youtu.be/5EwW8ZkArL4', 'youtube_id': '5EwW8ZkArL4', 'article': None, 'wikipedia': 'https://en.wikipedia.org/wiki/SpaceX_Crew-5'}, 'static_fire_date_utc': None, 'static_fire_date_unix': None, 'net': False, 'window': None, 'rocket': '5e9d0d95eda69973a809d1ec', 'success': True, 'failures': [], 'details': None, 'crew': ['62dd7196202306255024d13c', '62dd71c9202306255024d13d', '62dd7210202306255024d13e', '62dd7253202306255024d13f'], 'ships': [], 'capsules': ['617c05591bad2c661a6e2909'], 'payloads': ['62dd73ed202306255024d145'], 'launchpad': '5e9e4502f509094188566f88', 'flight_number': 1

### Using NumPy for Numerical Computations

In [18]:
import numpy as np

In [19]:
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [20]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# Element-wise addition
print("Addition:", a + b)

# Element-wise multiplication
print("Multiplication:", a * b)

# Mean and Standard Deviation
print("Mean:", np.mean(a))
print("Standard Deviation:", np.std(a))

Addition: [11 22 33]
Multiplication: [10 40 90]
Mean: 20.0
Standard Deviation: 8.16496580927726


In [ ]:
# Array of zeros
zeros = np.zeros((3, 3))
print("Zeros Array:\n", zeros)

# Array of ones
ones = np.ones((2, 2))
print("Ones Array:\n", ones)

# Identity Matrix
identity = np.eye(3)
print("Identity Matrix:\n", identity)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Data Analysis with pandas

In [ ]:
import pandas as pd

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print(df)

In [ ]:
# Read the CSV file
df = pd.read_csv('dummy_data.csv')

# Display the first few rows of the DataFrame
print(df.head())

In [ ]:
# Select the 'Name' column
names = df['Name']
print(names)

# Select multiple columns ('Name' and 'Salary')
names_and_salaries = df[['Name', 'Salary']]
print(names_and_salaries)

In [ ]:
# Select people aged 30 or older
age_30_or_older = df[df['Age'] >= 30]
print(age_30_or_older)

# Select people from a specific city (e.g., 'Seattle')
seattle_residents = df[df['City'] == 'Seattle']
print(seattle_residents)

In [ ]:
# Sort by Salary in descending order
sorted_by_salary = df.sort_values(by='Salary', ascending=False)
print(sorted_by_salary.head())

# Sort by Age in ascending order
sorted_by_age = df.sort_values(by='Age')
print(sorted_by_age.head())

In [ ]:
mean_age = df['Age'].mean()
print(f"Mean Age: {mean_age}")

# Calculate the mean of the 'Salary' column
mean_salary = df['Salary'].mean()
print(f"Mean Salary: ${mean_salary}")

### Data Visualization with matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# Data for stores and items sold
stores = ['Store A', 'Store B', 'Store C', 'Store D', 'Store E']
items_sold = [200, 450, 300, 500, 650]

# Create a bar chart
plt.bar(stores, items_sold, color='orange')

# Adding title and labels
plt.xlabel('Stores')
plt.ylabel('Items Sold')
plt.title('Items Sold by Each Store')

# Show the plot
plt.show()

In [ ]:
# Scatter plot for Age vs Salary
plt.scatter(df['Age'], df['Salary'], color='blue', alpha=1)

# Adding title and labels
plt.title('Age vs Salary Scatter Plot')
plt.xlabel('Age')
plt.ylabel('Salary')

# Show the plot
plt.show()

### Image Processing with OpenCV

In [ ]:
import cv2

In [ ]:
img = cv2.imread('sample_image.jpg')
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# Load the image in grayscale
img_gray = cv2.imread('sample_image.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('Gray Image', img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# Convert the image to RGB and display using matplotlib
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img_rgb)
plt.show()

In [ ]:
# Display the grayscale image using matplotlib
plt.imshow(img_gray, cmap='gray')
plt.show()

### Simple Machine Learning Classifier with MNIST dataset

In [ ]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
mnist = fetch_openml('mnist_784', version=1, data_home='data/')
X = mnist.data / 255.0  # Normalize pixel values
y = mnist.target.values.astype(int)


In [ ]:
# Display the first 5 images and their labels
fig, axes = plt.subplots(1, 5, figsize=(12, 6))

# Randomly select 5 indices from the test set
random_indices = np.random.choice(len(X), size=5, replace=False)

for i, idx in enumerate(random_indices):
    axes[i].imshow(X.iloc[idx].values.reshape(28, 28), cmap='gray')
    axes[i].set_title(f"Label: {y[idx]}")
    axes[i].axis('off')

plt.show()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

In [ ]:
# Evaluate model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy on MNIST: {accuracy * 100:.2f}%")

In [ ]:
# Randomly select 5 indices from the test set
random_indices = np.random.choice(len(X_test), size=5, replace=False)

# Display the images with predictions
fig, axes = plt.subplots(1, 5, figsize=(12, 6))

for i, idx in enumerate(random_indices):
    axes[i].imshow(X_test.iloc[idx].values.reshape(28, 28), cmap='gray')
    axes[i].set_title(f"Pred: {y_pred[idx]}")
    axes[i].axis('off')